### ISSUE TITLE
Feature request: React Native

### ISSUE THREAD

**Issue by jamesdwilson** [mattkrick/meatier#105] opened 2016-03-02 05:04 UTC
Please add support for react native

**Comment by mattkrick** [comment] 2016-03-02 16:09
Closing, duplicate of #38

**Closed by mattkrick** 2016-03-02 16:09 UTC

**Comment by jamesdwilson** [comment] 2016-03-02 17:02
sorry

On Wed, Mar 2, 2016 at 10:09 AM, Matt Krick <notifications@github.com>
wrote:

> Closed #105 <https://github.com/mattkrick/meatier/issues/105>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattkrick/meatier/issues/105#event-574881720>.
>



-- 
Thank you,

James D. Wilson
http://jameswilson.name
http://lnked.in/technologist
https://github.com/jamesdwilson
*https://twitter.com/thejamesdwilson <https://twitter.com/thejamesdwilson>*
