### ISSUE TITLE
Failling tests on example

### ISSUE THREAD

**Issue by gouroujo** [mattkrick/meatier#103] opened 2016-02-28 17:09 UTC
Hi,
When you launch tests just after install:
2 tests failed

  1. createUser:success
  AssertionError: { data:
    authToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImI3ZjIyODIxLTY
        _callee3$ (src/server/graphql/models/User/__tests___/userMutation-tests.js:226:15)

  2. createUser:alreadyexists
  AssertionError: { data:
    authToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk4YjM5NjZiLTd
        _callee4$ (src/server/graphql/models/User/__tests___/userMutation-tests.js:326:15)

After some investigation it seems  that `user.strategies.local` are not equal but I don't know how to fix the problem...

**Comment by gouroujo** [comment] 2016-02-28 17:19
@yatsu fix this in his fork with the following diff;

```
-  t.same(actual, expected)
+  t.same(actual.data.newUser.user.id, expected.data.newUser.user.id);
+  t.same(actual.data.newUser.user.email, expected.data.newUser.user.email);
+  t.same(actual.data.newUser.user.createdAt, expected.data.newUser.user.createdAt);
```

**Comment by yatsu** [comment] 2016-02-29 00:08
> @gouroujo

It is just a quick fix to pass the test.
I don't think it is a right solution.

**Comment by mattkrick** [comment] 2016-03-03 20:46
yeah, it's bizarre, i think there's a problem with the AVA deep equal algo in `t.same` but i haven't had time to investigate. If you find out anything more let me know or open up an issue over there

**Comment by Bartekus** [comment] 2016-03-10 05:04
So in AVA `t.true` means `val === true` and `t.same` means `deep strict equal`, this is different from what people that come from tape or tap might expect since tape's `t.same` means `deep non-strict equal` and `t.ok` is `!!val`

**Comment by Bartekus** [comment] 2016-03-10 05:49
The first test failure occurred in `createUser:success` due to an trailing error being attached to the actual result:
```
"errors": [
  {
    "message": "property.call is not a function",
    "originalError": {}
  }
```
otherwise actual and expected outputs are identical minus the added error in actual:

```
{
  "data": {
  "newUser": {
    "user": {
      "id": "0f6f6e07-d36f-42fc-9bd4-b6b54781ade4",
        "email": "createuser:success@createuser:success",
        "createdAt": null,
        "updatedAt": null,
        "strategies": {
        "local": {
          "isVerified": false,
            "password": null,
            "verifiedEmailToken": null,
            "resetToken": null
        },
        "google": null
      }
    },
    "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBmNmY2ZTA3LWQzNmYtNDJmYy05YmQ0LWI2YjU0NzgxYWRlNCIsImlhdCI6MTQ1NzU4Nzc4MywiZXhwIjoxNDU4MTkyNTgzfQ.z2PWWAekJ5RccX6lYvtUZQ3ImOPIlsvxGILlrrufAKs"
  }
},
  "errors": [
  {
    "message": "property.call is not a function",
    "originalError": {}
  }
]
}
```

vs

expected:
```
{
  "data": {
  "newUser": {
    "user": {
      "id": "0f6f6e07-d36f-42fc-9bd4-b6b54781ade4",
        "email": "createuser:success@createuser:success",
        "createdAt": null,
        "updatedAt": null,
        "strategies": {
        "local": {
          "isVerified": false,
            "password": null,
            "verifiedEmailToken": null,
            "resetToken": null
        },
        "google": null
      }
    },
    "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBmNmY2ZTA3LWQzNmYtNDJmYy05YmQ0LWI2YjU0NzgxYWRlNCIsImlhdCI6MTQ1NzU4Nzc4MywiZXhwIjoxNDU4MTkyNTgzfQ.z2PWWAekJ5RccX6lYvtUZQ3ImOPIlsvxGILlrrufAKs"
  }
}
}

```

**Comment by Bartekus** [comment] 2016-03-10 06:16
FYI yatsu fix is not bad way to circumvent what is most likely an error cause by updates to one of the modules used in the test. In a way running more concise test while not fixing the underlining issue being `property.call is not a function` is not optimal but it focuses on comparing apples to apples and all things equal, it proves that build works, albite artifacts are present in its current state.

So to pass both failing test yatsu replaced `t.same(actual, expected)` with:
```
t.same(actual.data.newUser.user.id, expected.data.newUser.user.id);
  t.same(actual.data.newUser.user.email, expected.data.newUser.user.email);
  t.same(actual.data.newUser.user.createdAt, expected.data.newUser.user.createdAt);
```

**Comment by mattkrick** [comment] 2016-03-10 12:30
Agree, the more declarative approach is nicer, just longer to write. I'll
try to fix it up today. I'm still curious why the deep equal is now
failing...

**Comment by mattkrick** [comment] 2016-03-10 16:25
Root cause is that both objects have to share the same constructor to be equal...

**Comment by mattkrick** [comment] 2016-03-13 18:08
fixed by https://github.com/sindresorhus/ava/pull/640. If this is an immediate concern you can pull the master branch of AVA from github, otherwise the npm package will be released this week with the fix.

**Comment by Bartekus** [comment] 2016-03-13 19:51
Well done @mattkrick and on behalf of the meatier/AVA community, thank you good sir!

**Comment by wenzowski** [comment] 2016-03-21 23:46
If we reset the db before running the test suite we get the following graphql error which is causing the inequality referenced above: 

```
TypeError: property.call is not a function
    at defaultResolveFn (./node_modules/graphql/execution/execute.js:600:54)
    at resolveOrError (./node_modules/graphql/execution/execute.js:426:12)
    at resolveField (./node_modules/graphql/execution/execute.js:417:16)
    at ./node_modules/graphql/execution/execute.js:235:18
    at Array.reduce (native)
    at executeFields (./node_modules/graphql/execution/execute.js:233:43)
    at completeValue (./node_modules/graphql/execution/execute.js:585:10)
    at completeValueCatchingError (./node_modules/graphql/execution/execute.js:446:21)
    at resolveField (./node_modules/graphql/execution/execute.js:419:10)
    at ./node_modules/graphql/execution/execute.js:235:18
    at Array.reduce (native)
    at executeFields (./node_modules/graphql/execution/execute.js:233:43)
    at completeValue (./node_modules/graphql/execution/execute.js:585:10)
    at ./node_modules/graphql/execution/execute.js:490:14
    at run (./node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at ./node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (./node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by mattkrick** [comment] 2016-03-22 00:33
@wenzowski sometimes i noticed that the first time i run a test graphQL returns an error object, even if there is no error. then, i run it again & it works as expected. is this in reference to that?

**Comment by wenzowski** [comment] 2016-03-22 01:07
Yes, @mattkrick this is that.
I'm hoping that if this turns out to be an upstream issue we can report it.
Haven't spent enough time digging through the graphql reference implementation to know what's going on offhand.

**Comment by wenzowski** [comment] 2016-03-24 20:20
The final issue appears to be caused by `call` becoming unbound in [defaultResolveFn](https://github.com/graphql/graphql-js/blob/b5ed31e6e3136accba13c3a4a5b7f61c36d7dcb4/src/executor/executor.js#L655)

**Comment by mattkrick** [comment] 2016-03-24 20:37
that's wild, thanks for finding it! are you use it's the `defaultResolveFn` that is in the graphQL package & not the one that is used in meatier? I had to copy it over to enable auth & i figure it's much more likely that my shoddy code is to blame instead of graphQL.

**Comment by wenzowski** [comment] 2016-03-24 20:43
Absolutely sure it's becoming unbound in the default graphql function [`at defaultResolveFn (/home/ubuntu/meatier/node_modules/graphql/execution/execute.js:600:54)`](https://circleci.com/gh/wenzowski/meatier/15) because the [upstream pr I submitted](https://github.com/graphql/graphql-js/pull/330) fixes it...though I have no idea what is causing `call` to become unbound offhand.

**Comment by mattkrick** [comment] 2016-03-24 20:51
oh man, great find! i'm stumped on that one as well, it'd be fun to dive in this weekend & see why...

**Closed** 2016-05-13 21:56 UTC
