### ISSUE TITLE
cordova integration 

### ISSUE THREAD

**Issue by mike623** [mattkrick/meatier#28] opened 2015-12-26 09:37 UTC
Is there any way to build for mobile ?

**Comment by mattkrick** [comment] 2015-12-26 15:18
sure, you *could* use cordova, but if you wanna go that route you might wanna stick with Meteor. IMO, a hybrid app isn't performant enough to be considered production quality. I'd recommend writing something in react native and *maybe* drop in a cordova plugin where you need certain hardware functionality. MVP = meteor, production = meatier.

**Comment by AdamBrodzinski** [comment] 2015-12-26 22:00
@mattkrick  agreed, React Native that consumes an API (or GraphQL) is 100x better. Been there done that. Not going back :see_no_evil:

**Comment by mattkrick** [comment] 2015-12-27 00:34
@AdamBrodzinski Now *that's* interesting. You saw a bottleneck in just the transport? I left hybrid because the animations looked janky, but if hybrid can't handle the basics like an http request...yikes! Were you able to track down the root cause?

**Comment by AdamBrodzinski** [comment] 2015-12-27 03:28
@mattkrick oh I just meant that React Native using an HTTP was in general 100x better than a Meteor Cordova setup.... mostly in workflow and plugin compatibility. The animations were also an issue but my previous app didn't really have crazy animations.

Cordova and Meteor did have some websocket issues (2 years ago) but those have been cleaned up with the new integration.

**Comment by mattkrick** [comment] 2015-12-27 15:34
ah gotcha, that makes sense. Yeah, reconnectivity is a fun topic with websockets, always a tradeoff between performance & durability. Closing this issue for now since I think the right answer is to just go native, but cordova is a viable alternative for anyone looking to implement it.

**Closed by mattkrick** 2015-12-27 15:34 UTC
