### ISSUE TITLE
update package.json

### ISSUE THREAD

**Issue by mydearxym** [mattkrick/meatier#148] opened 2016-04-23 14:56 UTC
it works fine but `npm install` get  some warnings:

![image](https://cloud.githubusercontent.com/assets/6184465/14762171/96bd98b2-09a6-11e6-865e-47c84b918cb8.png)

**Comment by mattkrick** [comment] 2016-04-23 15:13
duplicate of #107, #78

**Closed by mattkrick** 2016-04-23 15:13 UTC
